### ISSUE TITLE
KerbalStuff incompatible mods : ScienceAlert, USI-LS & USI OKS/MKS

### ISSUE THREAD

**Issue by maxix** [oharaandrew314/TinkerTime#266]
Hi Andrew,

the Science Alert (https://kerbalstuff.com/mod/424/ScienceAlert) mod throw this error when added :

![tinker1](https://cloud.githubusercontent.com/assets/982592/8788970/c8e635b2-2f3e-11e5-9fc6-f1f3a12070cb.png)

2015-07-21 00:25:55,679 [DEBUG] StatementBuilder built statement SELECT * FROM `modFiles` WHERE `mod_id` = ? 
2015-07-21 00:25:55,679 [DEBUG] BaseMappedStatement prepared statement 'SELECT * FROM `modFiles` WHERE `mod_id` = ? ' with 1 args
2015-07-21 00:25:55,680 [DEBUG] SelectIterator starting iterator @931907715 for 'SELECT * FROM `modFiles` WHERE `mod_id` = ? '
2015-07-21 00:25:55,680 [DEBUG] SelectIterator closed iterator @931907715 after 0 rows
2015-07-21 00:26:01,938 [DEBUG] BaseMappedStatement delete data with statement 'DELETE FROM `mods` WHERE `id` = ?' and 1 args, changed 1 rows
2015-07-21 00:26:01,938 [DEBUG] BaseMappedStatement update data with statement 'UPDATE `installations` SET `name` = ?, `path` = ? WHERE `id` = ?' and 3 args, changed 1 rows
2015-07-21 00:26:01,938 [DEBUG] BaseMappedStatement delete data with statement 'DELETE FROM `mods` WHERE `id` = ?' and 1 args, changed 0 rows
2015-07-21 00:26:05,071 [DEBUG] BaseMappedStatement delete data with statement 'DELETE FROM `mods` WHERE `id` = ?' and 1 args, changed 0 rows
2015-07-21 00:26:05,071 [DEBUG] BaseMappedStatement update data with statement 'UPDATE `installations` SET `name` = ?, `path` = ? WHERE `id` = ?' and 3 args, changed 1 rows
2015-07-21 00:26:05,071 [DEBUG] BaseMappedStatement delete data with statement 'DELETE FROM `mods` WHERE `id` = ?' and 1 args, changed 0 rows
2015-07-21 00:26:08,944 [DEBUG] BaseMappedStatement insert data with statement 'INSERT INTO `mods` (`updatedOn` ,`name` ,`creator` ,`modVersion` ,`kspVersion` ,`url` ,`updateAvailable` ,`builtIn` ,`installation_id` ,`imageBytes` ,`readmeText` ) VALUES (?,?,?,?,?,?,?,?,?,?,?)' and 11 args, changed 1 rows
2015-07-21 00:26:08,945 [DEBUG] BaseMappedStatement assigned id '48' from keyholder to 'id' in Mod object
2015-07-21 00:26:08,945 [DEBUG] BaseMappedStatement update data with statement 'UPDATE `installations` SET `name` = ?, `path` = ? WHERE `id` = ?' and 3 args, changed 1 rows
javax.imageio.IIOException: Invalid argument to native writeImage
        at com.sun.imageio.plugins.jpeg.JPEGImageWriter.writeImage(Native Method)
        at com.sun.imageio.plugins.jpeg.JPEGImageWriter.writeOnThread(JPEGImageWriter.java:1058)
        at com.sun.imageio.plugins.jpeg.JPEGImageWriter.write(JPEGImageWriter.java:360)
        at javax.imageio.ImageWriter.write(ImageWriter.java:615)
        at javax.imageio.ImageIO.doWrite(ImageIO.java:1612)
        at javax.imageio.ImageIO.write(ImageIO.java:1578)
        at io.andrewohara.tinkertime.models.mod.Mod.setImage(Mod.java:120)
        at io.andrewohara.tinkertime.controllers.workflows.tasks.DownloadModImageTask.execute(DownloadModImageTask.java:43)
        at io.andrewohara.common.workflows.tasks.WorkflowTask.call(WorkflowTask.java:67)
        at io.andrewohara.common.workflows.Workflow.run(Workflow.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)

**Comment by maxix** [comment]
The same error was encountered with USI Kolonisation Systems (https://kerbalstuff.com/mod/788/USI%20Kolonization%20Systems%20%28MKS/OKS%29)




2015-07-21 00:35:06,779 [DEBUG] BaseMappedStatement insert data with statement 'INSERT INTO `mods` (`updatedOn` ,`name` ,`creator` ,`modVersion` ,`kspVersion` ,`url` ,`updateAvailable` ,`builtIn` ,`installation_id` ,`imageBytes` ,`readmeText` ) VALUES (?,?,?,?,?,?,?,?,?,?,?)' and 11 args, changed 1 rows
2015-07-21 00:35:06,779 [DEBUG] BaseMappedStatement assigned id '57' from keyholder to 'id' in Mod object
2015-07-21 00:35:06,779 [DEBUG] BaseMappedStatement update data with statement 'UPDATE `installations` SET `name` = ?, `path` = ? WHERE `id` = ?' and 3 args, changed 1 rows
javax.imageio.IIOException: Invalid argument to native writeImage
        at com.sun.imageio.plugins.jpeg.JPEGImageWriter.writeImage(Native Method)
        at com.sun.imageio.plugins.jpeg.JPEGImageWriter.writeOnThread(JPEGImageWriter.java:1058)
        at com.sun.imageio.plugins.jpeg.JPEGImageWriter.write(JPEGImageWriter.java:360)
        at javax.imageio.ImageWriter.write(ImageWriter.java:615)
        at javax.imageio.ImageIO.doWrite(ImageIO.java:1612)
        at javax.imageio.ImageIO.write(ImageIO.java:1578)
        at io.andrewohara.tinkertime.models.mod.Mod.setImage(Mod.java:120)
        at io.andrewohara.tinkertime.controllers.workflows.tasks.DownloadModImageTask.execute(DownloadModImageTask.java:43)
        at io.andrewohara.common.workflows.tasks.WorkflowTask.call(WorkflowTask.java:67)
        at io.andrewohara.common.workflows.Workflow.run(Workflow.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)

**Comment by maxix** [comment]
And of course the same happens whith USI Life Support (https://kerbalstuff.com/mod/963/USI%20Life%20Support)

**Comment by oharaandrew314** [comment]
This appears to be Linux-specific, unless it can be reproduced on OSX as well.  Will investigate.

**Comment by oharaandrew314** [comment]
No, this actually appears to be an OpenJDK issue (good thing I was running it on my Linux VM).  OpenJDK doesn't support JPG encoding.  So any mod that has an image will fail.  I don't support OpenJDK, but this was an easy-enough fix to make.

**Comment by maxix** [comment]
I do confirm that the bug is resolved with 2.0.1 

Thanks!
