### ISSUE TITLE
KerbalStuff incompatible mod : Magic Smoke Industries Infernal Robotics 

### ISSUE THREAD

**Issue by maxix** [oharaandrew314/TinkerTime#267]
Hi Andrew,

when adding the mod Magic Smoke Industries Infernal Robotics (https://kerbalstuff.com/mod/8/Magic_Smoke_Industries_Infernal_Robotics) i encounter this error :

![tinker2](https://cloud.githubusercontent.com/assets/982592/8789087/c28fc0e2-2f3f-11e5-8c1c-e1729fdd6f43.png)

2015-07-21 00:31:57,339 [DEBUG] BaseMappedStatement insert data with statement 'INSERT INTO `mods` (`updatedOn` ,`name` ,`creator` ,`modVersion` ,`kspVersion` ,`url` ,`updateAvailable` ,`builtIn` ,`installation_id` ,`imageBytes` ,`readmeText` ) VALUES (?,?,?,?,?,?,?,?,?,?,?)' and 11 args, changed 1 rows
2015-07-21 00:31:57,340 [DEBUG] BaseMappedStatement assigned id '54' from keyholder to 'id' in Mod object
2015-07-21 00:31:57,340 [DEBUG] BaseMappedStatement update data with statement 'UPDATE `installations` SET `name` = ?, `path` = ? WHERE `id` = ?' and 3 args, changed 1 rows
java.lang.RuntimeException: invalid arguments
        at io.andrewohara.common.content.ImageManager.scaleToFit(ImageManager.java:83)
        at io.andrewohara.tinkertime.controllers.workflows.tasks.DownloadModImageTask.execute(DownloadModImageTask.java:42)
        at io.andrewohara.common.workflows.tasks.WorkflowTask.call(WorkflowTask.java:67)
        at io.andrewohara.common.workflows.Workflow.run(Workflow.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)

**Comment by maxix** [comment]
I indeed do confirm that the bug is resolved with 2.0.1 

:)
