### ISSUE TITLE
curse incompatible mods : Mechjeb, Mechjeb Embedded, Tac Fuel Bal., Kas, Biosuits

### ISSUE THREAD

**Issue by maxix** [oharaandrew314/TinkerTime#268]
Hi Andrew,

i found these Curse incompatible mods with Tinker 2.0.0 with the following error :
* Mechjeb (http://www.curse.com/ksp-mods/kerbal/220221-mechjeb)
* Mechjeb Embedded Universal (http://www.curse.com/ksp-mods/kerbal/221109-mechjeb-embedded-universal)
* Tac Fuel Balancer (http://www.curse.com/ksp-mods/kerbal/221160-tac-fuel-balancer)
* KAS (http://www.curse.com/ksp-mods/kerbal/223900-kerbal-attachment-system-kas)
* Biosuits (http://www.curse.com/ksp-mods/kerbal/227077-biosuits)

![tinker3](https://cloud.githubusercontent.com/assets/982592/8789509/4df8485e-2f43-11e5-962f-e0eab08bf817.png)

2015-07-21 00:53:53,159 [DEBUG] BaseMappedStatement insert data with statement 'INSERT INTO `mods` (`updatedOn` ,`name` ,`creator` ,`modVersion` ,`kspVersion` ,`url` ,`updateAvailable` ,`builtIn` ,`installation_id` ,`imageBytes` ,`readmeText` ) VALUES (?,?,?,?,?,?,?,?,?,?,?)' and 11 args, changed 1 rows
2015-07-21 00:53:53,159 [DEBUG] BaseMappedStatement assigned id '72' from keyholder to 'id' in Mod object
2015-07-21 00:53:53,159 [DEBUG] BaseMappedStatement update data with statement 'UPDATE `installations` SET `name` = ?, `path` = ? WHERE `id` = ?' and 3 args, changed 1 rows
Exception in thread "AWT-EventQueue-0" java.lang.IndexOutOfBoundsException: Index: 2, Size: 2
        at java.util.ArrayList.rangeCheck(ArrayList.java:635)
        at java.util.ArrayList.get(ArrayList.java:411)
        at java.awt.Container.createHierarchyEvents(Container.java:1434)
        at java.awt.Container.addImpl(Container.java:1134)
        at javax.swing.CellRendererPane.addImpl(CellRendererPane.java:106)
        at java.awt.Container.add(Container.java:410)
        at javax.swing.CellRendererPane.paintComponent(CellRendererPane.java:134)
        at javax.swing.plaf.basic.BasicListUI.paintCell(BasicListUI.java:226)
        at javax.swing.plaf.basic.BasicListUI.paintImpl(BasicListUI.java:316)
        at javax.swing.plaf.basic.BasicListUI.paint(BasicListUI.java:239)
        at javax.swing.plaf.ComponentUI.update(ComponentUI.java:161)
        at javax.swing.JComponent.paintComponent(JComponent.java:770)
        at javax.swing.JComponent.paint(JComponent.java:1046)
        at javax.swing.JComponent.paintChildren(JComponent.java:879)
        at javax.swing.JComponent.paint(JComponent.java:1055)
        at javax.swing.JViewport.paint(JViewport.java:731)
        at javax.swing.JComponent.paintChildren(JComponent.java:879)
        at javax.swing.JComponent.paint(JComponent.java:1055)
        at javax.swing.JComponent.paintChildren(JComponent.java:879)
        at javax.swing.JComponent.paint(JComponent.java:1055)
        at javax.swing.JComponent.paintChildren(JComponent.java:879)
        at javax.swing.JSplitPane.paintChildren(JSplitPane.java:1047)
        at javax.swing.JComponent.paint(JComponent.java:1055)
        at javax.swing.JComponent.paintChildren(JComponent.java:879)
        at javax.swing.JComponent.paint(JComponent.java:1055)
        at javax.swing.JComponent.paintChildren(JComponent.java:879)
        at javax.swing.JComponent.paint(JComponent.java:1055)
        at javax.swing.JLayeredPane.paint(JLayeredPane.java:585)
        at javax.swing.JComponent.paintToOffscreen(JComponent.java:5223)
        at javax.swing.BufferStrategyPaintManager.paint(BufferStrategyPaintManager.java:295)
        at javax.swing.RepaintManager.paint(RepaintManager.java:1249)
        at javax.swing.JComponent._paintImmediately(JComponent.java:5171)
        at javax.swing.JComponent.paintImmediately(JComponent.java:4982)
        at javax.swing.RepaintManager$3.run(RepaintManager.java:808)
        at javax.swing.RepaintManager$3.run(RepaintManager.java:796)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
        at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:796)
        at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:769)
        at javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:718)
        at javax.swing.RepaintManager.access$1100(RepaintManager.java:62)
        at javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1677)
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:312)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:745)
        at java.awt.EventQueue.access$300(EventQueue.java:103)
        at java.awt.EventQueue$3.run(EventQueue.java:706)
        at java.awt.EventQueue$3.run(EventQueue.java:704)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:715)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
javax.imageio.IIOException: Invalid argument to native writeImage
        at com.sun.imageio.plugins.jpeg.JPEGImageWriter.writeImage(Native Method)
        at com.sun.imageio.plugins.jpeg.JPEGImageWriter.writeOnThread(JPEGImageWriter.java:1058)
        at com.sun.imageio.plugins.jpeg.JPEGImageWriter.write(JPEGImageWriter.java:360)
        at javax.imageio.ImageWriter.write(ImageWriter.java:615)
        at javax.imageio.ImageIO.doWrite(ImageIO.java:1612)
        at javax.imageio.ImageIO.write(ImageIO.java:1578)
        at io.andrewohara.tinkertime.models.mod.Mod.setImage(Mod.java:120)
        at io.andrewohara.tinkertime.controllers.workflows.tasks.DownloadModImageTask.execute(DownloadModImageTask.java:43)
        at io.andrewohara.common.workflows.tasks.WorkflowTask.call(WorkflowTask.java:67)
        at io.andrewohara.common.workflows.Workflow.run(Workflow.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)

**Comment by oharaandrew314** [comment]
Closing as dup of #266
