### ISSUE TITLE
Unchecked Execution Exception java error

### ISSUE THREAD

**Issue by antydoom** [oharaandrew314/TinkerTime#269]
any idea what this means?
![java error](https://cloud.githubusercontent.com/assets/7883530/8808371/2901ea6a-2fb0-11e5-868a-e7e1766264bd.JPG)

**Comment by oharaandrew314** [comment]
No clue.  Think you could run TT in a console and get me the stracktrace?

**Comment by antydoom** [comment]
not a clue on how to do that?

**Comment by oharaandrew314** [comment]
1. Copy TT to your Desktop
2. Open Command Prompt
3. Execute `cd Desktop`
4. Execute `java -jar TinkerTime.jar`

This will run TT in a console.  When you reproduce the error, you should get a bunch of output.  To copy the output:

1. Right-click on the top bar of the window
2. Go to Edit > Mark
3. Select all the output and press Enter to copy
4. Paste it here

**Comment by oharaandrew314** [comment]
Some steps to reproduce the problem would be even more useful though.  Then I could just get the stacktrace myself.

**Comment by antydoom** [comment]
now would all of it be output or am i looking for something specific?

**Comment by oharaandrew314** [comment]
There will probably be a bunch of db operations at the start.  Get me the everything past the first time you see something about an exception.

**Comment by antydoom** [comment]
Exception in thread "AWT-EventQueue-0" java.lang.IndexOutOfBoundsException: Inde
x: 2, Size: 2
        at java.util.ArrayList.rangeCheck(Unknown Source)
        at java.util.ArrayList.get(Unknown Source)
        at java.awt.Container.createHierarchyEvents(Unknown Source)
        at java.awt.Container.addImpl(Unknown Source)
        at javax.swing.CellRendererPane.addImpl(Unknown Source)
        at java.awt.Container.add(Unknown Source)
        at javax.swing.CellRendererPane.paintComponent(Unknown Source)
        at javax.swing.plaf.basic.BasicListUI.paintCell(Unknown Source)
        at javax.swing.plaf.basic.BasicListUI.paintImpl(Unknown Source)
        at javax.swing.plaf.basic.BasicListUI.paint(Unknown Source)
        at javax.swing.plaf.ComponentUI.update(Unknown Source)
        at javax.swing.JComponent.paintComponent(Unknown Source)
        at javax.swing.JComponent.paint(Unknown Source)
        at javax.swing.JComponent.paintChildren(Unknown Source)
        at javax.swing.JComponent.paint(Unknown Source)
        at javax.swing.JViewport.paint(Unknown Source)
        at javax.swing.JComponent.paintChildren(Unknown Source)
        at javax.swing.JComponent.paint(Unknown Source)
        at javax.swing.JComponent.paintChildren(Unknown Source)
        at javax.swing.JComponent.paint(Unknown Source)
        at javax.swing.JComponent.paintChildren(Unknown Source)
        at javax.swing.JSplitPane.paintChildren(Unknown Source)
        at javax.swing.JComponent.paint(Unknown Source)
        at javax.swing.JComponent.paintChildren(Unknown Source)
        at javax.swing.JComponent.paint(Unknown Source)
        at javax.swing.JComponent.paintChildren(Unknown Source)
        at javax.swing.JComponent.paint(Unknown Source)
        at javax.swing.JLayeredPane.paint(Unknown Source)
        at javax.swing.JComponent.paintChildren(Unknown Source)
        at javax.swing.JComponent.paintToOffscreen(Unknown Source)
        at javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(Unknown S
ource)
        at javax.swing.RepaintManager$PaintManager.paint(Unknown Source)
        at javax.swing.RepaintManager.paint(Unknown Source)
        at javax.swing.JComponent.paint(Unknown Source)
        at java.awt.GraphicsCallback$PaintCallback.run(Unknown Source)
        at sun.awt.SunGraphicsCallback.runOneComponent(Unknown Source)
        at sun.awt.SunGraphicsCallback.runComponents(Unknown Source)
        at java.awt.Container.paint(Unknown Source)
        at java.awt.Window.paint(Unknown Source)
        at javax.swing.RepaintManager$4.run(Unknown Source)
        at javax.swing.RepaintManager$4.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Sour
ce)
        at javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
        at javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
        at javax.swing.RepaintManager.prePaintDirtyRegions(Unknown Source)
        at javax.swing.RepaintManager.access$1300(Unknown Source)
        at javax.swing.RepaintManager$ProcessingRunnable.run(Unknown Source)
        at java.awt.event.InvocationEvent.dispatch(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Sour
ce)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)
com.google.common.util.concurrent.UncheckedExecutionException: java.util.NoSuchE
lementException
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2201)
        at com.google.common.cache.LocalCache.get(LocalCache.java:3934)
        at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3938)
        at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.j
ava:4821)
        at io.andrewohara.tinkertime.io.crawlers.pageLoaders.PageLoader.getPage(
PageLoader.java:44)
        at io.andrewohara.tinkertime.io.crawlers.Crawler.getPage(Crawler.java:10
9)
        at io.andrewohara.tinkertime.io.crawlers.CurseCrawler.getNewestAssets(Cu
rseCrawler.java:69)
        at io.andrewohara.tinkertime.io.crawlers.Crawler.getSelectedAsset(Crawle
r.java:133)
        at io.andrewohara.tinkertime.io.crawlers.Crawler.getVersion(Crawler.java
:120)
        at io.andrewohara.tinkertime.io.crawlers.Crawler.isUpdateAvailable(Crawl
er.java:73)
        at io.andrewohara.tinkertime.controllers.workflows.tasks.CheckForUpdateT
ask.execute(CheckForUpdateTask.java:30)
        at io.andrewohara.common.workflows.tasks.WorkflowTask.call(WorkflowTask.
java:67)
        at io.andrewohara.common.workflows.Workflow.run(Workflow.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.util.NoSuchElementException
        at java.util.LinkedList.getLast(Unknown Source)
        at org.jsoup.parser.TreeBuilder.currentElement(TreeBuilder.java:58)
        at org.jsoup.parser.HtmlTreeBuilder.insertNode(HtmlTreeBuilder.java:247)

        at org.jsoup.parser.HtmlTreeBuilder.insert(HtmlTreeBuilder.java:195)
        at org.jsoup.parser.HtmlTreeBuilder.insert(HtmlTreeBuilder.java:184)
        at org.jsoup.parser.HtmlTreeBuilderState$6.process(HtmlTreeBuilderState.
java:209)
        at org.jsoup.parser.HtmlTreeBuilder.process(HtmlTreeBuilder.java:111)
        at org.jsoup.parser.HtmlTreeBuilderState$6.anythingElse(HtmlTreeBuilderS
tate.java:241)
        at org.jsoup.parser.HtmlTreeBuilderState$6.process(HtmlTreeBuilderState.
java:225)
        at org.jsoup.parser.HtmlTreeBuilder.process(HtmlTreeBuilder.java:111)
        at org.jsoup.parser.HtmlTreeBuilderState$4.anythingElse(HtmlTreeBuilderS
tate.java:163)
        at org.jsoup.parser.HtmlTreeBuilderState$4.process(HtmlTreeBuilderState.
java:139)
        at org.jsoup.parser.HtmlTreeBuilder.process(HtmlTreeBuilder.java:111)
        at org.jsoup.parser.HtmlTreeBuilderState$3.process(HtmlTreeBuilderState.
java:89)
        at org.jsoup.parser.HtmlTreeBuilder.process(HtmlTreeBuilder.java:111)
        at org.jsoup.parser.HtmlTreeBuilderState$2.anythingElse(HtmlTreeBuilderS
tate.java:63)
        at org.jsoup.parser.HtmlTreeBuilderState$2.process(HtmlTreeBuilderState.
java:55)
        at org.jsoup.parser.HtmlTreeBuilder.process(HtmlTreeBuilder.java:111)
        at org.jsoup.parser.HtmlTreeBuilderState$1.process(HtmlTreeBuilderState.
java:32)
        at org.jsoup.parser.HtmlTreeBuilder.process(HtmlTreeBuilder.java:111)
        at org.jsoup.parser.TreeBuilder.runParser(TreeBuilder.java:48)
        at org.jsoup.parser.TreeBuilder.parse(TreeBuilder.java:41)
        at org.jsoup.parser.HtmlTreeBuilder.parse(HtmlTreeBuilder.java:54)
        at org.jsoup.parser.Parser.parseInput(Parser.java:30)
        at org.jsoup.helper.DataUtil.parseByteData(DataUtil.java:120)
        at org.jsoup.helper.HttpConnection$Response.parse(HttpConnection.java:51
7)
        at org.jsoup.helper.HttpConnection.get(HttpConnection.java:168)
        at io.andrewohara.tinkertime.io.crawlers.pageLoaders.WebpageLoader.loadP
age(WebpageLoader.java:27)
        at io.andrewohara.tinkertime.io.crawlers.pageLoaders.WebpageLoader.loadP
age(WebpageLoader.java:15)
        at io.andrewohara.tinkertime.io.crawlers.pageLoaders.PageLoader$1.load(P
ageLoader.java:35)
        at io.andrewohara.tinkertime.io.crawlers.pageLoaders.PageLoader$1.load(P
ageLoader.java:32)
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(L
ocalCache.java:3524)
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2
317)
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache
.java:2280)
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2195)
        ... 15 more
com.google.common.util.concurrent.UncheckedExecutionException: java.util.NoSuchE
lementException
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2201)
        at com.google.common.cache.LocalCache.get(LocalCache.java:3934)
        at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3938)
        at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.j
ava:4821)
        at io.andrewohara.tinkertime.io.crawlers.pageLoaders.PageLoader.getPage(
PageLoader.java:44)
        at io.andrewohara.tinkertime.io.crawlers.Crawler.getPage(Crawler.java:10
9)
        at io.andrewohara.tinkertime.io.crawlers.CurseCrawler.getNewestAssets(Cu
rseCrawler.java:69)
        at io.andrewohara.tinkertime.io.crawlers.Crawler.getSelectedAsset(Crawle
r.java:133)
        at io.andrewohara.tinkertime.io.crawlers.Crawler.getVersion(Crawler.java
:120)
        at io.andrewohara.tinkertime.io.crawlers.Crawler.isUpdateAvailable(Crawl
er.java:73)
        at io.andrewohara.tinkertime.controllers.workflows.tasks.CheckForUpdateT
ask.execute(CheckForUpdateTask.java:30)
        at io.andrewohara.common.workflows.tasks.WorkflowTask.call(WorkflowTask.
java:67)
        at io.andrewohara.common.workflows.Workflow.run(Workflow.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.util.NoSuchElementException
        at java.util.LinkedList.getLast(Unknown Source)
        at org.jsoup.parser.TreeBuilder.currentElement(TreeBuilder.java:58)
        at org.jsoup.parser.HtmlTreeBuilder.insertNode(HtmlTreeBuilder.java:247)

        at org.jsoup.parser.HtmlTreeBuilder.insert(HtmlTreeBuilder.java:195)
        at org.jsoup.parser.HtmlTreeBuilder.insert(HtmlTreeBuilder.java:184)
        at org.jsoup.parser.HtmlTreeBuilderState$6.process(HtmlTreeBuilderState.
java:209)
        at org.jsoup.parser.HtmlTreeBuilder.process(HtmlTreeBuilder.java:111)
        at org.jsoup.parser.HtmlTreeBuilderState$6.anythingElse(HtmlTreeBuilderS
tate.java:241)
        at org.jsoup.parser.HtmlTreeBuilderState$6.process(HtmlTreeBuilderState.
java:225)
        at org.jsoup.parser.HtmlTreeBuilder.process(HtmlTreeBuilder.java:111)
        at org.jsoup.parser.HtmlTreeBuilderState$4.anythingElse(HtmlTreeBuilderS
tate.java:163)
        at org.jsoup.parser.HtmlTreeBuilderState$4.process(HtmlTreeBuilderState.
java:139)
        at org.jsoup.parser.HtmlTreeBuilder.process(HtmlTreeBuilder.java:111)
        at org.jsoup.parser.HtmlTreeBuilderState$3.process(HtmlTreeBuilderState.
java:89)
        at org.jsoup.parser.HtmlTreeBuilder.process(HtmlTreeBuilder.java:111)
        at org.jsoup.parser.HtmlTreeBuilderState$2.anythingElse(HtmlTreeBuilderS
tate.java:63)
        at org.jsoup.parser.HtmlTreeBuilderState$2.process(HtmlTreeBuilderState.
java:55)
        at org.jsoup.parser.HtmlTreeBuilder.process(HtmlTreeBuilder.java:111)
        at org.jsoup.parser.HtmlTreeBuilderState$1.process(HtmlTreeBuilderState.
java:32)
        at org.jsoup.parser.HtmlTreeBuilder.process(HtmlTreeBuilder.java:111)
        at org.jsoup.parser.TreeBuilder.runParser(TreeBuilder.java:48)
        at org.jsoup.parser.TreeBuilder.parse(TreeBuilder.java:41)
        at org.jsoup.parser.HtmlTreeBuilder.parse(HtmlTreeBuilder.java:54)
        at org.jsoup.parser.Parser.parseInput(Parser.java:30)
        at org.jsoup.helper.DataUtil.parseByteData(DataUtil.java:120)
        at org.jsoup.helper.HttpConnection$Response.parse(HttpConnection.java:51
7)
        at org.jsoup.helper.HttpConnection.get(HttpConnection.java:168)
        at io.andrewohara.tinkertime.io.crawlers.pageLoaders.WebpageLoader.loadP
age(WebpageLoader.java:27)
        at io.andrewohara.tinkertime.io.crawlers.pageLoaders.WebpageLoader.loadP
age(WebpageLoader.java:15)
        at io.andrewohara.tinkertime.io.crawlers.pageLoaders.PageLoader$1.load(P
ageLoader.java:35)
        at io.andrewohara.tinkertime.io.crawlers.pageLoaders.PageLoader$1.load(P
ageLoader.java:32)
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(L
ocalCache.java:3524)
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2
317)
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache
.java:2280)
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2195)
        ... 15 more
com.google.common.util.concurrent.UncheckedExecutionException: java.util.NoSuchE
lementException
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2201)
        at com.google.common.cache.LocalCache.get(LocalCache.java:3934)
        at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3938)
        at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.j
ava:4821)
        at io.andrewohara.tinkertime.io.crawlers.pageLoaders.PageLoader.getPage(
PageLoader.java:44)
        at io.andrewohara.tinkertime.io.crawlers.Crawler.getPage(Crawler.java:10
9)
        at io.andrewohara.tinkertime.io.crawlers.CurseCrawler.getNewestAssets(Cu
rseCrawler.java:69)
        at io.andrewohara.tinkertime.io.crawlers.Crawler.getSelectedAsset(Crawle
r.java:133)
        at io.andrewohara.tinkertime.io.crawlers.Crawler.getVersion(Crawler.java
:120)
        at io.andrewohara.tinkertime.io.crawlers.Crawler.isUpdateAvailable(Crawl
er.java:73)
        at io.andrewohara.tinkertime.controllers.workflows.tasks.CheckForUpdateT
ask.execute(CheckForUpdateTask.java:30)
        at io.andrewohara.common.workflows.tasks.WorkflowTask.call(WorkflowTask.
java:67)
        at io.andrewohara.common.workflows.Workflow.run(Workflow.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.util.NoSuchElementException
        at java.util.LinkedList.getLast(Unknown Source)
        at org.jsoup.parser.TreeBuilder.currentElement(TreeBuilder.java:58)
        at org.jsoup.parser.HtmlTreeBuilder.insert(HtmlTreeBuilder.java:237)
        at org.jsoup.parser.HtmlTreeBuilderState$4.process(HtmlTreeBuilderState.
java:97)
        at org.jsoup.parser.HtmlTreeBuilder.process(HtmlTreeBuilder.java:111)
        at org.jsoup.parser.TreeBuilder.runParser(TreeBuilder.java:48)
        at org.jsoup.parser.TreeBuilder.parse(TreeBuilder.java:41)
        at org.jsoup.parser.HtmlTreeBuilder.parse(HtmlTreeBuilder.java:54)
        at org.jsoup.parser.Parser.parseInput(Parser.java:30)
        at org.jsoup.helper.DataUtil.parseByteData(DataUtil.java:120)
        at org.jsoup.helper.HttpConnection$Response.parse(HttpConnection.java:51
7)
        at org.jsoup.helper.HttpConnection.get(HttpConnection.java:168)
        at io.andrewohara.tinkertime.io.crawlers.pageLoaders.WebpageLoader.loadP
age(WebpageLoader.java:27)
        at io.andrewohara.tinkertime.io.crawlers.pageLoaders.WebpageLoader.loadP
age(WebpageLoader.java:15)
        at io.andrewohara.tinkertime.io.crawlers.pageLoaders.PageLoader$1.load(P
ageLoader.java:35)
        at io.andrewohara.tinkertime.io.crawlers.pageLoaders.PageLoader$1.load(P
ageLoader.java:32)
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(L
ocalCache.java:3524)
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2
317)
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache
.java:2280)
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2195)
        ... 15 more

**Comment by oharaandrew314** [comment]
Ok, something's wrong with how I'm using google's in-memory expiry cache for caching pages.

What mod are you trying to download when you get this?  Can you give me the URL?

**Comment by antydoom** [comment]
im gonna try it once more, it was on startup of TT.

**Comment by antydoom** [comment]
now it seems i can't get it past the splash screen.

**Comment by oharaandrew314** [comment]
Um... very strange.  Your database may be corrupt.  Try deleting it at:
`My Documents/TinkerTime/TinkerTime-db`

**Comment by antydoom** [comment]
ok got it log is giving me an IO exception.

**Comment by antydoom** [comment]
db.mv or db.trace?

**Comment by antydoom** [comment]
or just wipe the folder?

**Comment by oharaandrew314** [comment]
Delete both of the db files.  Wiping the folder shouldn't make a difference.  the json files aren't used anymore.

Can you paste that exception, too?

Sorry about the issues.  I converted TT to use a database, and I've never built my own SQL Db application from the ground-up before, or used the Java H2 database.

**Comment by antydoom** [comment]
love its way smoother but still seems to have a slight mem leak

**Comment by oharaandrew314** [comment]
Yeah, the database lets me cache a whole bunch of things to make it faster (like readme text, and zip contents).  I just noticed that the memory leak was still there last night.  I thought I had fixed that, but obviously not.

**Comment by antydoom** [comment]
the leak seems to happen after a few mods are added or if TT is left running for long.

as for the errors it may have been one or more of the mods, im going to try a fresh install of ksp.

**Comment by oharaandrew314** [comment]
A fresh install of KSP shouldn't make a difference.

I didn't know that adding mods sprung the leak, too.  I've only encountered the leak after leaving it running for ~40+ minutes.

**Comment by antydoom** [comment]
well there seemed to be some leftover mods that were still running when i changed to 2.0

**Comment by oharaandrew314** [comment]
Hey @antydoom, is there still an issue here?  If so, can you give me the steps to reproduce it?  Also, maybe try the new version I just released.  It has a tool which lets you get the stacktrace if it catches the error in a dialog.

**Comment by antydoom** [comment]
yeah it may have been a corrupted database, ill try out 2.0.1 and get back to you.

**Comment by antydoom** [comment]
love the exception viewer.

**Comment by antydoom** [comment]
alright heres another stack trace for same error.

UncheckedExecutionException on 2015-07-26T23-02-19Z: java.lang.IllegalArgumentException: String must not be empty
com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalArgumentException: String must not be empty
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2201)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3934)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3938)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4821)
	at io.andrewohara.tinkertime.io.crawlers.pageLoaders.PageLoader.getPage(PageLoader.java:44)
	at io.andrewohara.tinkertime.io.crawlers.Crawler.getPage(Crawler.java:109)
	at io.andrewohara.tinkertime.io.crawlers.CurseCrawler.getNewestAssets(CurseCrawler.java:69)
	at io.andrewohara.tinkertime.io.crawlers.Crawler.getSelectedAsset(Crawler.java:133)
	at io.andrewohara.tinkertime.io.crawlers.Crawler.getVersion(Crawler.java:120)
	at io.andrewohara.tinkertime.io.crawlers.Crawler.isUpdateAvailable(Crawler.java:73)
	at io.andrewohara.tinkertime.controllers.workflows.tasks.CheckForUpdateTask.execute(CheckForUpdateTask.java:30)
	at io.andrewohara.common.workflows.tasks.WorkflowTask.call(WorkflowTask.java:67)
	at io.andrewohara.common.workflows.Workflow.run(Workflow.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: String must not be empty
	at org.jsoup.helper.Validate.notEmpty(Validate.java:92)
	at org.jsoup.nodes.Attribute.<init>(Attribute.java:22)
	at org.jsoup.parser.Token$Tag.newAttribute(Token.java:62)
	at org.jsoup.parser.TokeniserState$36.read(TokeniserState.java:723)
	at org.jsoup.parser.Tokeniser.read(Tokeniser.java:42)
	at org.jsoup.parser.TreeBuilder.runParser(TreeBuilder.java:47)
	at org.jsoup.parser.TreeBuilder.parse(TreeBuilder.java:41)
	at org.jsoup.parser.HtmlTreeBuilder.parse(HtmlTreeBuilder.java:54)
	at org.jsoup.parser.Parser.parseInput(Parser.java:30)
	at org.jsoup.helper.DataUtil.parseByteData(DataUtil.java:120)
	at org.jsoup.helper.HttpConnection$Response.parse(HttpConnection.java:517)
	at org.jsoup.helper.HttpConnection.get(HttpConnection.java:168)
	at io.andrewohara.tinkertime.io.crawlers.pageLoaders.WebpageLoader.loadPage(WebpageLoader.java:27)
	at io.andrewohara.tinkertime.io.crawlers.pageLoaders.WebpageLoader.loadPage(WebpageLoader.java:15)
	at io.andrewohara.tinkertime.io.crawlers.pageLoaders.PageLoader$1.load(PageLoader.java:35)
	at io.andrewohara.tinkertime.io.crawlers.pageLoaders.PageLoader$1.load(PageLoader.java:32)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3524)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2317)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2280)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2195)
	... 15 more
UncheckedExecutionException on 2015-07-26T23-02-19Z: java.lang.IllegalArgumentException: String must not be empty
com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalArgumentException: String must not be empty
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2201)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3934)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3938)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4821)
	at io.andrewohara.tinkertime.io.crawlers.pageLoaders.PageLoader.getPage(PageLoader.java:44)
	at io.andrewohara.tinkertime.io.crawlers.Crawler.getPage(Crawler.java:109)
	at io.andrewohara.tinkertime.io.crawlers.CurseCrawler.getNewestAssets(CurseCrawler.java:69)
	at io.andrewohara.tinkertime.io.crawlers.Crawler.getSelectedAsset(Crawler.java:133)
	at io.andrewohara.tinkertime.io.crawlers.Crawler.getVersion(Crawler.java:120)
	at io.andrewohara.tinkertime.io.crawlers.Crawler.isUpdateAvailable(Crawler.java:73)
	at io.andrewohara.tinkertime.controllers.workflows.tasks.CheckForUpdateTask.execute(CheckForUpdateTask.java:30)
	at io.andrewohara.common.workflows.tasks.WorkflowTask.call(WorkflowTask.java:67)
	at io.andrewohara.common.workflows.Workflow.run(Workflow.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: String must not be empty
	at org.jsoup.helper.Validate.notEmpty(Validate.java:92)
	at org.jsoup.nodes.Attribute.<init>(Attribute.java:22)
	at org.jsoup.parser.Token$Tag.newAttribute(Token.java:62)
	at org.jsoup.parser.TokeniserState$36.read(TokeniserState.java:718)
	at org.jsoup.parser.Tokeniser.read(Tokeniser.java:42)
	at org.jsoup.parser.TreeBuilder.runParser(TreeBuilder.java:47)
	at org.jsoup.parser.TreeBuilder.parse(TreeBuilder.java:41)
	at org.jsoup.parser.HtmlTreeBuilder.parse(HtmlTreeBuilder.java:54)
	at org.jsoup.parser.Parser.parseInput(Parser.java:30)
	at org.jsoup.helper.DataUtil.parseByteData(DataUtil.java:120)
	at org.jsoup.helper.HttpConnection$Response.parse(HttpConnection.java:517)
	at org.jsoup.helper.HttpConnection.get(HttpConnection.java:168)
	at io.andrewohara.tinkertime.io.crawlers.pageLoaders.WebpageLoader.loadPage(WebpageLoader.java:27)
	at io.andrewohara.tinkertime.io.crawlers.pageLoaders.WebpageLoader.loadPage(WebpageLoader.java:15)
	at io.andrewohara.tinkertime.io.crawlers.pageLoaders.PageLoader$1.load(PageLoader.java:35)
	at io.andrewohara.tinkertime.io.crawlers.pageLoaders.PageLoader$1.load(PageLoader.java:32)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3524)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2317)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2280)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2195)
	... 15 more

**Comment by antydoom** [comment]
i think this one came from importing the mods then restarting since nothing showed during import.

**Comment by oharaandrew314** [comment]
Does this happen when yo're checking for mod updates?  Can you give me a list of the mods you have?  Preferably, just the one that is causing this error.
