### ISSUE TITLE
NoSuchElement from 2 fresheCurse

### ISSUE THREAD

**Issue by maxix** [oharaandrew314/TinkerTime#273]
Upon a full update check with TT 2.0.1 Linux OpenJDK, got an NoSuchElement error with 2 mods (KAS & MechJebEmbeddedUniversal from Curse). These were installed fine, then restart tt, check all, error. 

Then a call to wine when i click on open stacktrace so no stacktrace ;)

![tinker3](https://cloud.githubusercontent.com/assets/982592/8896238/f595058c-33f5-11e5-888a-3e15d5faa1b1.png)

2015-07-27 00:13:05,775 [DEBUG] SelectIterator closed iterator @806882873 after 10 rows
2015-07-27 00:13:05,777 [DEBUG] StatementBuilder built statement SELECT * FROM `modFiles` WHERE `mod_id` = ? 
2015-07-27 00:13:05,777 [DEBUG] BaseMappedStatement prepared statement 'SELECT * FROM `modFiles` WHERE `mod_id` = ? ' with 1 args
2015-07-27 00:13:05,777 [DEBUG] SelectIterator starting iterator @1792257381 for 'SELECT * FROM `modFiles` WHERE `mod_id` = ? '
2015-07-27 00:13:05,778 [DEBUG] SelectIterator closed iterator @1792257381 after 70 rows
2015-07-27 00:13:05,780 [DEBUG] StatementBuilder built statement SELECT * FROM `modFiles` WHERE `mod_id` = ? 
2015-07-27 00:13:05,780 [DEBUG] BaseMappedStatement prepared statement 'SELECT * FROM `modFiles` WHERE `mod_id` = ? ' with 1 args
2015-07-27 00:13:05,781 [DEBUG] SelectIterator starting iterator @1986651674 for 'SELECT * FROM `modFiles` WHERE `mod_id` = ? '
2015-07-27 00:13:05,781 [DEBUG] SelectIterator closed iterator @1986651674 after 4 rows
com.google.common.util.concurrent.UncheckedExecutionException: java.lang.NullPointerException
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2201)
        at com.google.common.cache.LocalCache.get(LocalCache.java:3934)
        at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3938)
        at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4821)
        at io.andrewohara.tinkertime.io.crawlers.pageLoaders.PageLoader.getPage(PageLoader.java:44)
        at io.andrewohara.tinkertime.io.crawlers.Crawler.getPage(Crawler.java:109)
        at io.andrewohara.tinkertime.io.crawlers.CurseCrawler.getNewestAssets(CurseCrawler.java:69)
        at io.andrewohara.tinkertime.io.crawlers.Crawler.getSelectedAsset(Crawler.java:133)
        at io.andrewohara.tinkertime.io.crawlers.Crawler.getVersion(Crawler.java:120)
        at io.andrewohara.tinkertime.io.crawlers.Crawler.isUpdateAvailable(Crawler.java:73)
        at io.andrewohara.tinkertime.controllers.workflows.tasks.CheckForUpdateTask.execute(CheckForUpdateTask.java:30)
        at io.andrewohara.common.workflows.tasks.WorkflowTask.call(WorkflowTask.java:67)
        at io.andrewohara.common.workflows.Workflow.run(Workflow.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
        at org.jsoup.parser.HtmlTreeBuilder.pop(HtmlTreeBuilder.java:258)
        at org.jsoup.parser.HtmlTreeBuilderState$4.process(HtmlTreeBuilderState.java:146)
        at org.jsoup.parser.HtmlTreeBuilder.process(HtmlTreeBuilder.java:111)
        at org.jsoup.parser.HtmlTreeBuilderState$4.anythingElse(HtmlTreeBuilderState.java:162)
        at org.jsoup.parser.HtmlTreeBuilderState$4.process(HtmlTreeBuilderState.java:139)
        at org.jsoup.parser.HtmlTreeBuilder.process(HtmlTreeBuilder.java:111)
        at org.jsoup.parser.HtmlTreeBuilderState$3.process(HtmlTreeBuilderState.java:89)
        at org.jsoup.parser.HtmlTreeBuilder.process(HtmlTreeBuilder.java:111)
        at org.jsoup.parser.HtmlTreeBuilderState$2.anythingElse(HtmlTreeBuilderState.java:63)
        at org.jsoup.parser.HtmlTreeBuilderState$2.process(HtmlTreeBuilderState.java:55)
        at org.jsoup.parser.HtmlTreeBuilder.process(HtmlTreeBuilder.java:111)
        at org.jsoup.parser.HtmlTreeBuilderState$1.process(HtmlTreeBuilderState.java:32)
        at org.jsoup.parser.HtmlTreeBuilder.process(HtmlTreeBuilder.java:111)
        at org.jsoup.parser.TreeBuilder.runParser(TreeBuilder.java:48)
        at org.jsoup.parser.TreeBuilder.parse(TreeBuilder.java:41)
        at org.jsoup.parser.HtmlTreeBuilder.parse(HtmlTreeBuilder.java:54)
        at org.jsoup.parser.Parser.parseInput(Parser.java:30)
        at org.jsoup.helper.DataUtil.parseByteData(DataUtil.java:120)
        at org.jsoup.helper.HttpConnection$Response.parse(HttpConnection.java:517)
        at org.jsoup.helper.HttpConnection.get(HttpConnection.java:168)
        at io.andrewohara.tinkertime.io.crawlers.pageLoaders.WebpageLoader.loadPage(WebpageLoader.java:27)
        at io.andrewohara.tinkertime.io.crawlers.pageLoaders.WebpageLoader.loadPage(WebpageLoader.java:15)
        at io.andrewohara.tinkertime.io.crawlers.pageLoaders.PageLoader$1.load(PageLoader.java:35)
        at io.andrewohara.tinkertime.io.crawlers.pageLoaders.PageLoader$1.load(PageLoader.java:32)
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3524)
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2317)
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2280)
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2195)
        ... 15 more
com.google.common.util.concurrent.UncheckedExecutionException: java.util.NoSuchElementException
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2201)
        at com.google.common.cache.LocalCache.get(LocalCache.java:3934)
        at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3938)
        at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4821)
        at io.andrewohara.tinkertime.io.crawlers.pageLoaders.PageLoader.getPage(PageLoader.java:44)
        at io.andrewohara.tinkertime.io.crawlers.Crawler.getPage(Crawler.java:109)
        at io.andrewohara.tinkertime.io.crawlers.CurseCrawler.getNewestAssets(CurseCrawler.java:86)
        at io.andrewohara.tinkertime.io.crawlers.Crawler.getSelectedAsset(Crawler.java:133)
        at io.andrewohara.tinkertime.io.crawlers.Crawler.getVersion(Crawler.java:120)
        at io.andrewohara.tinkertime.io.crawlers.Crawler.isUpdateAvailable(Crawler.java:73)
        at io.andrewohara.tinkertime.controllers.workflows.tasks.CheckForUpdateTask.execute(CheckForUpdateTask.java:30)
        at io.andrewohara.common.workflows.tasks.WorkflowTask.call(WorkflowTask.java:67)
        at io.andrewohara.common.workflows.Workflow.run(Workflow.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.NoSuchElementException
        at java.util.LinkedList.getLast(LinkedList.java:255)
        at org.jsoup.parser.TreeBuilder.currentElement(TreeBuilder.java:58)
        at org.jsoup.parser.HtmlTreeBuilder.insert(HtmlTreeBuilder.java:233)
        at org.jsoup.parser.HtmlTreeBuilderState$4.process(HtmlTreeBuilderState.java:97)
        at org.jsoup.parser.HtmlTreeBuilder.process(HtmlTreeBuilder.java:111)
        at org.jsoup.parser.TreeBuilder.runParser(TreeBuilder.java:48)
        at org.jsoup.parser.TreeBuilder.parse(TreeBuilder.java:41)
        at org.jsoup.parser.HtmlTreeBuilder.parse(HtmlTreeBuilder.java:54)
        at org.jsoup.parser.Parser.parseInput(Parser.java:30)
        at org.jsoup.helper.DataUtil.parseByteData(DataUtil.java:120)
        at org.jsoup.helper.HttpConnection$Response.parse(HttpConnection.java:517)
        at org.jsoup.helper.HttpConnection.get(HttpConnection.java:168)
        at io.andrewohara.tinkertime.io.crawlers.pageLoaders.WebpageLoader.loadPage(WebpageLoader.java:27)
        at io.andrewohara.tinkertime.io.crawlers.pageLoaders.WebpageLoader.loadPage(WebpageLoader.java:15)
        at io.andrewohara.tinkertime.io.crawlers.pageLoaders.PageLoader$1.load(PageLoader.java:35)
        at io.andrewohara.tinkertime.io.crawlers.pageLoaders.PageLoader$1.load(PageLoader.java:32)
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3524)
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2317)
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2280)
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2195)
        ... 15 more
env: wine: Aucun fichier ou dossier de ce type
env: wine: Aucun fichier ou dossier de ce type
env: wine: Aucun fichier ou dossier de ce type
env: wine: Aucun fichier ou dossier de ce type
env: wine: Aucun fichier ou dossier de ce type
env: wine: Aucun fichier ou dossier de ce type
env: wine: Aucun fichier ou dossier de ce type

**Comment by oharaandrew314** [comment]
I should have time this weekend to investigate this.
